version: "3.9"

services:
  web:
    build: .
    environment:
      DEBUG: "${DEBUG}"
      SECRET: "${SECRET}"
    # command: ./start
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"