# Generated by Django 3.0.13 on 2021-03-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('website', '0004_bookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='coderedpage_ptr',
        ),
        migrations.RemoveField(
            model_name='bookslistingpage',
            name='coderedpage_ptr',
        ),
        migrations.DeleteModel(
            name='BookIndexPage',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='BooksListingPage',
        ),
    ]
