# Generated by Django 3.0.13 on 2021-03-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_formpagefield_clean_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpagefield',
            name='clean_name',
        ),
    ]
