# Generated by Django 3.0.13 on 2021-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210317_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslistingpage',
            name='flat_menu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
