# Generated by Django 3.0.13 on 2021-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookslistingpage_flat_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslistingpage',
            name='flat_menu',
        ),
        migrations.AddField(
            model_name='bookindexpage',
            name='flat_menu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
