# Generated by Django 3.0.13 on 2021-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210317_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookindexpage',
            name='flat_menu',
            field=models.CharField(blank=True, help_text='Si no está en la lista, se asignará automáticamente cuando crees la página', max_length=255, null=True),
        ),
    ]
